name: Build e Publicação de imagem Docker
on:
  push:
    branches: ["main"] # dispara apenas ao realizar merge ou push na main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código-fonte
        uses: actions/checkout@v4

      # Novo Passo 1: Configurar o ambiente do Node.js no servidor do GitHub
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajuste para a versão do seu projeto se necessário

      # Novo Passo 2: Instalar todas as dependências (incluindo o @eslint/js)
      - name: Instalar dependências do projeto
        run: npm ci

      # Novo Passo 3: Executar o linter para validar o código antes do Docker
      - name: Executar Linter
        run: npm run lint

      # step 2: configurar o Docker Buildx
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # step 3: autenticar no DockerHub usando secrets
      - name: Autenticar no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # step 4: extrair metadados para versionamento inteligente
      - name: Extrair metadados do docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/minha-aplicacao
          tags: |
            type=raw,value=latest
            type=sha,format=short

      # step 5: construir e publicar (build and push)
      - name: Construir e Publicar imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
